#!/usr/bin/bash

PLUGIN_UUID="ja@axelingolfsson.gmail.com"
DATA_DIR="data"

main() {
    if [ $1 = "zip" ]; then
        create_zip
    elif [ $1 = "live" ]; then
        setup_live
    elif [ $1 = "enable" ]; then
        enable_extension
    elif [ $1 = "disable" ]; then
        disable_extension
    elif [ $1 = "remove" ]; then
        remove_extension
    elif [ $1 = "help" ]; then
        help
    fi
}

check_data() {
    # Check if folder data exists, if not, create it
    if [ ! -d $DATA_DIR ]
    then
        echo "Creating directory data"
        mkdir $DATA_DIR
    fi
}

create_zip() {
    check_data
    zipcommand="zip -j data/"$PLUGIN_UUID".zip "$PLUGIN_UUID"/*"
    $zipcommand
}

setup_live() {
    `cp -r $PLUGIN_UUID ~/.local/share/gnome-shell/extensions/`
}

enable_extension() {
    `gnome-shell-extension-tool -e $PLUGIN_UUID`
}

disable_extension() {
    `gnome-shell-extension-tool -d $PLUGIN_UUID`
}

remove_extension() {
    `rm -r ~/.local/share/gnome-shell/extensions/$PLUGIN_UUID`
}

help() {
    echo "./manage zip      # Create a zip file under data/ ready for extensions.gnome.org"
    echo "./manage live     # Setup the extension on this maschine"
    echo "./manage remove   # Remove the extension from this maschine"
    echo "./manage enable   # Enable the extension"
    echo "./manage disable  # Disable the extension"
    echo "./manage help     # Show this help message"
}

main "$@"
